/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pharmacie;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

/**
 *
 * @author zking
 */
public class JDUnPdt extends javax.swing.JDialog {
    private Produit leProduit;
    private String action;
    private JDProduits Produits;

    /**
     * Creates new form JDUnProduit
     */
    public JDUnPdt(java.awt.Frame parent, boolean modal,Produit pPdt,String pAction) {
        initComponents();
        leProduit=pPdt;
        if(leProduit!=null){
            txtId.setText(leProduit.getId()+"");
            txtId.setEditable(false);
            txtLib.setText(leProduit.getLibelle()+"");
            txtLoc.setText(leProduit.getLocalisation()+"");
            txtPrix.setText(leProduit.getPrix()+"");
            txtQtte.setText(leProduit.getQuantite()+"");
            txtQtteCrit.setText(leProduit.getSeuilCrit()+"");
        }
        action=pAction;
        btnValid.setText("Valider " + action);
        if(action.equals("ajouter")){
            btnSuppr.setVisible(false);
        }else{
            btnSuppr.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblLib = new javax.swing.JLabel();
        lblPrix = new javax.swing.JLabel();
        lblQtte = new javax.swing.JLabel();
        lblLoc = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtLib = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        txtQtte = new javax.swing.JTextField();
        txtLoc = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSuppr = new javax.swing.JButton();
        btnValid = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtQtteCrit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitre.setText("Edition de produit");

        lblId.setText("Id du produit :");

        lblLib.setText("Libellé :");

        lblPrix.setText("Prix :");

        lblQtte.setText("Quantité :");

        lblLoc.setText("Localisation :");

        btnCancel.setText("Annuler");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        btnSuppr.setText("Supprimer un produit");
        btnSuppr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprMouseClicked(evt);
            }
        });

        btnValid.setText("Valider");
        btnValid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValidMouseClicked(evt);
            }
        });

        jLabel1.setText("Quantité Critique");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnCancel)
                        .addGap(103, 103, 103)
                        .addComponent(btnSuppr))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitre)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLib)
                                    .addComponent(lblId)
                                    .addComponent(lblPrix)
                                    .addComponent(lblQtte)
                                    .addComponent(lblLoc)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txtLib, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txtPrix, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txtQtte, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txtLoc, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txtQtteCrit))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(btnValid)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTitre)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLib)
                    .addComponent(txtLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrix)
                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtte)
                    .addComponent(txtQtte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoc)
                    .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQtteCrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSuppr)
                    .addComponent(btnValid))
                .addGap(105, 105, 105))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Produits=new JDProduits(null, true);
        Produits.setVisible(true);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSupprMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprMouseClicked
        Passerelle.supprimerProduit(Passerelle.donnerUnProduit(parseInt(txtId.getText())));
        txtId.setText("");
        txtLib.setText("");
        txtPrix.setText("");
        txtQtte.setText("");
        txtLoc.setText("");
        txtQtteCrit.setText("");
    }//GEN-LAST:event_btnSupprMouseClicked

    private void btnValidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidMouseClicked
        if(btnValid.getText().contains("ajouter")){
            Produit p1 = new Produit(parseInt(txtId.getText()),txtLib.getText(),parseDouble(txtPrix.getText()),parseInt(txtQtte.getText()),txtLoc.getText(),parseInt(txtQtteCrit.getText()));
            Passerelle.ajouterProduit(p1);
            txtId.setText("");
            txtLib.setText("");
            txtPrix.setText("");
            txtQtte.setText("");
            txtLoc.setText("");
            txtQtteCrit.setText("");
        }         
        if(btnValid.getText().contains("modifier")){
            int id = parseInt(txtId.getText());
            String libelle;
            double prix;
            int quantite;
            String localisation;
            int seuilCrit;
            if(txtLib.getText().equals("")){
                libelle = Passerelle.donnerUnProduit(id).getLibelle();  
            }
            else{
                libelle = txtLib.getText();
            }
            if(txtPrix.getText().equals("")){
                prix = Passerelle.donnerUnProduit(id).getPrix();            
            }
            else{
                prix = parseDouble(txtPrix.getText());
            }
            if(txtQtte.getText().equals("")){
                quantite = Passerelle.donnerUnProduit(id).getQuantite();
            }
            else{
                quantite = parseInt(txtQtte.getText());           
            }
            if(txtLoc.getText().equals("")){
                localisation = Passerelle.donnerUnProduit(id).getLocalisation();
            }
            else{
                localisation = txtLoc.getText();
            }
            if(txtQtteCrit.getText().equals("")){
                seuilCrit = Passerelle.donnerUnProduit(id).getSeuilCrit();
            }
            else{
                seuilCrit = parseInt(txtQtteCrit.getText());
            }
            Produit p2 = new Produit(id,libelle,prix,quantite,localisation,seuilCrit);
            Passerelle.modifierProduit(p2);     
            txtId.setText("");
            txtLib.setText("");
            txtPrix.setText("");
            txtQtte.setText("");
            txtLoc.setText("");
            txtQtteCrit.setText("");
        }
    }//GEN-LAST:event_btnValidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDUnPdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDUnPdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDUnPdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDUnPdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDUnPdt dialog = new JDUnPdt(new javax.swing.JFrame(), true,null,"ajouter");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSuppr;
    private javax.swing.JButton btnValid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLib;
    private javax.swing.JLabel lblLoc;
    private javax.swing.JLabel lblPrix;
    private javax.swing.JLabel lblQtte;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLib;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtQtte;
    private javax.swing.JTextField txtQtteCrit;
    // End of variables declaration//GEN-END:variables
}
