/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pharmacie;

/**
 *
 * @author kban6
 */

public class JDUneSortie extends javax.swing.JDialog {

    /**
     * Creates new form JDUneSortie
     */
    private Sortie laSortie;
    private JDSorties Sortie;
    
    public JDUneSortie(java.awt.Frame parent, boolean modal, Sortie laSortie) {
        super(parent, modal);
        initComponents();
        this.laSortie = laSortie;
        txtEmploye.setText(laSortie.getUtilisateur() + "");
        txtEmploye.setEditable(false);
        txtDateSortie.setText(laSortie.getDateSortie() + "");
        txtDateSortie.setEditable(false);
        txtProduitSortie.setText(laSortie.getLibelleProduit() + "");
        txtProduitSortie.setEditable(false);
        txtQtteSortie.setText(laSortie.getNbProduits()+ "");
        txtQtteSortie.setEditable(false);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmploye = new javax.swing.JTextField();
        txtDateSortie = new javax.swing.JTextField();
        txtProduitSortie = new javax.swing.JTextField();
        txtQtteSortie = new javax.swing.JTextField();
        lblInfoSortie = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ValiderBtn = new javax.swing.JToggleButton();
        nePasValiderBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeActionPerformed(evt);
            }
        });

        txtDateSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateSortieActionPerformed(evt);
            }
        });

        txtProduitSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduitSortieActionPerformed(evt);
            }
        });

        lblInfoSortie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoSortie.setText("Information sur cette Sortie");
        lblInfoSortie.setAlignmentX(0.5F);

        btnPDF.setText("Télécharger la sortie en PDF");

        btnQuitter.setText("Quitter");
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitterMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employé ayant effectué cette sortie :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date de la sortie :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Produit concerné :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quantité sortie :");

        ValiderBtn.setText("Valider Sortie");
        ValiderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValiderBtnMouseClicked(evt);
            }
        });

        nePasValiderBtn.setText("Ne Pas Valider Sortie");
        nePasValiderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nePasValiderBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnPDF)
                .addGap(28, 28, 28)
                .addComponent(ValiderBtn)
                .addGap(39, 39, 39)
                .addComponent(nePasValiderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnQuitter)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmploye)
                            .addComponent(txtDateSortie)
                            .addComponent(txtProduitSortie)
                            .addComponent(txtQtteSortie)
                            .addComponent(lblInfoSortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblInfoSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtDateSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtProduitSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQtteSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitter)
                    .addComponent(btnPDF)
                    .addComponent(ValiderBtn)
                    .addComponent(nePasValiderBtn))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProduitSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduitSortieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduitSortieActionPerformed

    private void txtEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeActionPerformed

    private void txtDateSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateSortieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateSortieActionPerformed

    private void btnQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseClicked
        this.dispose();
        Sortie=new JDSorties(null, true);
        Sortie.setVisible(true);
    }//GEN-LAST:event_btnQuitterMouseClicked

    private void ValiderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValiderBtnMouseClicked
        // TODO add your handling code here:
        // BTN valider SORTIE
        int idAdmin = Passerelle.lEmploye.getId();
        // Sortie laSortie = Sortie.getSortieByID();
        Passerelle.validerSortie(laSortie, idAdmin, true);
        
    }//GEN-LAST:event_ValiderBtnMouseClicked

    private void nePasValiderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nePasValiderBtnMouseClicked
        // TODO add your handling code here:
        // BTN NE PAS VALIDER SORTIE
        int idAdmin = Passerelle.lEmploye.getId();
        // Sortie laSortie = Sortie.getSortieByID();
        Passerelle.validerSortie(laSortie, idAdmin, false);
    }//GEN-LAST:event_nePasValiderBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDUneSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDUneSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDUneSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDUneSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDUneSortie dialog = new JDUneSortie(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ValiderBtn;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblInfoSortie;
    private javax.swing.JToggleButton nePasValiderBtn;
    private javax.swing.JTextField txtDateSortie;
    private javax.swing.JTextField txtEmploye;
    private javax.swing.JTextField txtProduitSortie;
    private javax.swing.JTextField txtQtteSortie;
    // End of variables declaration//GEN-END:variables
}
